// ============================================================
// preguntas.js — Banco de preguntas School v4
// LOMLOE 6º Primaria — 260 preguntas
// ============================================================

const PREGUNTAS = {

  // ===================== MATEMÁTICAS (50) =====================
  matematicas: [
    {id:1, pregunta:"¿Cuánto es 3/4 + 1/4?", opciones:["1","2/4","1/2","3/8"], correcta:0, explicacion:"3/4 + 1/4 = 4/4 = 1."},
    {id:2, pregunta:"¿Cuál es el resultado de 5 × (3 + 2)?", opciones:["25","15","20","10"], correcta:0, explicacion:"Paréntesis primero: 3+2=5, luego 5×5=25."},
    {id:3, pregunta:"¿Cuántas aristas tiene un cubo?", opciones:["8","12","6","10"], correcta:1, explicacion:"Un cubo tiene 12 aristas."},
    {id:4, pregunta:"¿Cuál es el 25 % de 200?", opciones:["25","50","75","100"], correcta:1, explicacion:"200 × 0,25 = 50."},
    {id:5, pregunta:"¿Qué fracción es equivalente a 2/4?", opciones:["1/2","3/4","2/3","1/3"], correcta:0, explicacion:"2/4 simplificado = 1/2."},
    {id:6, pregunta:"Área de un rectángulo de 5 cm × 3 cm:", opciones:["15 cm²","8 cm²","16 cm²","10 cm²"], correcta:0, explicacion:"A = b × h = 15 cm²."},
    {id:7, pregunta:"¿Cuántos metros hay en 2,5 km?", opciones:["250","2500","25000","25"], correcta:1, explicacion:"1 km = 1000 m → 2500 m."},
    {id:8, pregunta:"¿Cuánto es (−3) + 5?", opciones:["2","8","−8","−2"], correcta:0, explicacion:"(−3)+5 = 2."},
    {id:9, pregunta:"¿Qué ángulo mide exactamente 90°?", opciones:["Agudo","Obtuso","Recto","Llano"], correcta:2, explicacion:"El ángulo recto mide 90°."},
    {id:10, pregunta:"¿Cuál es la moda de {2,3,3,5,7}?", opciones:["2","3","5","7"], correcta:1, explicacion:"3 es el valor que más se repite."},
    {id:11, pregunta:"¿Cuánto es 0,5 + 0,75?", opciones:["1,25","1,15","0,125","1,75"], correcta:0, explicacion:"0,5 + 0,75 = 1,25."},
    {id:12, pregunta:"Triángulo con tres lados iguales:", opciones:["Isósceles","Escaleno","Equilátero","Rectángulo"], correcta:2, explicacion:"Equilátero = 3 lados iguales."},
    {id:13, pregunta:"¿Cuánto es 3²?", opciones:["6","9","12","27"], correcta:1, explicacion:"3² = 3×3 = 9."},
    {id:14, pregunta:"mcm de 4 y 6:", opciones:["12","24","6","2"], correcta:0, explicacion:"Múltiplos: 4→4,8,12; 6→6,12 → mcm=12."},
    {id:15, pregunta:"¿Cuántos gramos hay en 1,5 kg?", opciones:["150","1500","15000","15"], correcta:1, explicacion:"1 kg=1000 g → 1500 g."},
    {id:16, pregunta:"Perímetro de un cuadrado de lado 7 cm:", opciones:["14 cm","21 cm","28 cm","49 cm"], correcta:2, explicacion:"P = 4×7 = 28 cm."},
    {id:17, pregunta:"¿Cuánto es 2/3 de 90?", opciones:["30","45","60","75"], correcta:2, explicacion:"(90÷3)×2 = 60."},
    {id:18, pregunta:"¿Qué número es divisible por 3 y por 5?", opciones:["10","12","15","20"], correcta:2, explicacion:"15÷3=5 y 15÷5=3."},
    {id:19, pregunta:"Media aritmética de 4, 6 y 8:", opciones:["5","6","7","8"], correcta:1, explicacion:"(4+6+8)÷3 = 6."},
    {id:20, pregunta:"¿Cuántos ml hay en 2 litros?", opciones:["200","2000","20","20000"], correcta:1, explicacion:"1 l = 1000 ml → 2000 ml."},
    {id:21, pregunta:"¿Cuánto es (−4) × (−2)?", opciones:["−8","8","−6","6"], correcta:1, explicacion:"Negativo × negativo = positivo → 8."},
    {id:22, pregunta:"x + 7 = 12 → x = ?", opciones:["4","5","6","7"], correcta:1, explicacion:"x = 12−7 = 5."},
    {id:23, pregunta:"¿Cuántas caras tiene un prisma triangular?", opciones:["4","5","6","3"], correcta:1, explicacion:"2 bases + 3 laterales = 5 caras."},
    {id:24, pregunta:"¿Qué fracción es mayor: 3/5 o 2/5?", opciones:["3/5","2/5","Son iguales","No se pueden comparar"], correcta:0, explicacion:"Mismo denominador → mayor numerador gana."},
    {id:25, pregunta:"10 % de 350:", opciones:["3,5","35","350","70"], correcta:1, explicacion:"350 × 0,10 = 35."},
    {id:26, pregunta:"Vértices de una pirámide cuadrangular:", opciones:["4","5","6","8"], correcta:1, explicacion:"4 base + 1 cúspide = 5."},
    {id:27, pregunta:"1/2 × 1/3 = ?", opciones:["1/6","1/5","2/3","2/6"], correcta:0, explicacion:"(1×1)/(2×3) = 1/6."},
    {id:28, pregunta:"Triángulo con un ángulo de 90°:", opciones:["Equilátero","Isósceles","Rectángulo","Obtusángulo"], correcta:2, explicacion:"Triángulo rectángulo = un ángulo de 90°."},
    {id:29, pregunta:"MCD de 12 y 18:", opciones:["3","6","9","12"], correcta:1, explicacion:"Divisores comunes máximos → 6."},
    {id:30, pregunta:"4,2 − 1,8 = ?", opciones:["2,4","2,6","3,4","2,2"], correcta:0, explicacion:"4,2 − 1,8 = 2,4."},
    {id:31, pregunta:"Polígono de 6 lados:", opciones:["Pentágono","Hexágono","Heptágono","Octógono"], correcta:1, explicacion:"Hexágono = 6 lados."},
    {id:32, pregunta:"Pizza de 8 porciones, comes 3. ¿Qué fracción queda?", opciones:["3/8","5/8","4/8","6/8"], correcta:1, explicacion:"8−3=5 → 5/8."},
    {id:33, pregunta:"15 ÷ 0,5 = ?", opciones:["7,5","30","3","10"], correcta:1, explicacion:"Dividir entre 0,5 = multiplicar por 2 → 30."},
    {id:34, pregunta:"Volumen de un cubo de arista 3 cm:", opciones:["9 cm³","18 cm³","27 cm³","12 cm³"], correcta:2, explicacion:"V = 3³ = 27 cm³."},
    {id:35, pregunta:"7/7 = ?", opciones:["0","7","1","0,7"], correcta:2, explicacion:"Cualquier nº entre sí mismo = 1."},
    {id:36, pregunta:"3 cuadernos cuestan 6 €. ¿9 cuadernos?", opciones:["12 €","15 €","18 €","21 €"], correcta:2, explicacion:"1 cuaderno=2 € → 9×2=18 €."},
    {id:37, pregunta:"¿Qué número es primo?", opciones:["4","9","15","7"], correcta:3, explicacion:"7 solo divisible por 1 y 7."},
    {id:38, pregunta:"Recta que divide un círculo por la mitad:", opciones:["Radio","Cuerda","Diámetro","Tangente"], correcta:2, explicacion:"El diámetro pasa por el centro."},
    {id:39, pregunta:"3/4 − 1/2 = ?", opciones:["1/2","1/4","2/4","3/2"], correcta:1, explicacion:"3/4 − 2/4 = 1/4."},
    {id:40, pregunta:"¿Cuántos cm³ hay en 1 litro?", opciones:["100","1000","10","10000"], correcta:1, explicacion:"1 l = 1000 cm³."},
    {id:41, pregunta:"¿Qué es un número compuesto?", opciones:["Más de 2 divisores","Solo 2 divisores","Negativo","Decimal"], correcta:0, explicacion:"Compuesto = más de 2 divisores."},
    {id:42, pregunta:"Escala 1:10 000. 5 cm en mapa = ¿real?", opciones:["500 m","5 km","50 m","50 km"], correcta:0, explicacion:"5×10000=50000 cm=500 m."},
    {id:43, pregunta:"(−6) ÷ 2 = ?", opciones:["3","−3","12","−12"], correcta:1, explicacion:"(−6)÷2 = −3."},
    {id:44, pregunta:"¿Cuál es irracional?", opciones:["3/4","0,5","√2","2"], correcta:2, explicacion:"√2 no se puede expresar como fracción."},
    {id:45, pregunta:"¿Cuántas caras tiene un cilindro?", opciones:["2","3","1","4"], correcta:1, explicacion:"2 bases + 1 lateral = 3 superficies."},
    {id:46, pregunta:"50 % de 80 + 25 % de 80 = ?", opciones:["40","60","70","80"], correcta:1, explicacion:"40+20 = 60."},
    {id:47, pregunta:"Ángulo de las agujas a las 3 en punto:", opciones:["60°","90°","120°","180°"], correcta:1, explicacion:"A las 3 = ángulo recto = 90°."},
    {id:48, pregunta:"Redondear 4,567 a las décimas:", opciones:["4,5","4,6","4,56","5"], correcta:1, explicacion:"Centésima=6 ≥ 5 → sube a 4,6."},
    {id:49, pregunta:"Suma ángulos interiores de un triángulo:", opciones:["90°","180°","270°","360°"], correcta:1, explicacion:"Siempre 180°."},
    {id:50, pregunta:"¿Qué se resuelve primero en 2+3×4?", opciones:["La suma","La multiplicación","Da igual","Ninguna"], correcta:1, explicacion:"Jerarquía: multiplicación antes que suma."},
  ],

  // ===================== LENGUA (50) =====================
  lengua: [
    {id:101, pregunta:"¿Qué tipo de palabra es 'rápidamente'?", opciones:["Adjetivo","Adverbio","Sustantivo","Verbo"], correcta:1, explicacion:"Adverbio de modo."},
    {id:102, pregunta:"Sujeto de 'El perro ladra fuerte':", opciones:["ladra","fuerte","El perro","perro ladra"], correcta:2, explicacion:"'El perro' realiza la acción."},
    {id:103, pregunta:"¿Qué es una metáfora?", opciones:["Comparación con 'como'","Identificar un elemento con otro","Exageración","Repetición de sonidos"], correcta:1, explicacion:"Identifica directamente sin usar 'como'."},
    {id:104, pregunta:"¿Cuál es esdrújula?", opciones:["Canción","Música","Reloj","Papel"], correcta:1, explicacion:"Mú-si-ca: tónica en antepenúltima."},
    {id:105, pregunta:"¿Qué tiempo verbal es 'cantaré'?", opciones:["Pretérito perfecto","Presente","Futuro simple","Pretérito imperfecto"], correcta:2, explicacion:"Futuro simple de indicativo."},
    {id:106, pregunta:"¿Qué signo introduce una enumeración?", opciones:["Punto y coma","Dos puntos","Coma","Punto y aparte"], correcta:1, explicacion:"Los dos puntos preceden a una enumeración."},
    {id:107, pregunta:"¿Qué es un diptongo?", opciones:["Dos vocales en sílabas distintas","Dos vocales en la misma sílaba","Tres vocales juntas","Una vocal sola"], correcta:1, explicacion:"Dos vocales en la misma sílaba."},
    {id:108, pregunta:"Un soneto pertenece al género:", opciones:["Narrativo","Dramático","Lírico","Didáctico"], correcta:2, explicacion:"Es poesía → género lírico."},
    {id:109, pregunta:"Antónimo de 'generoso':", opciones:["Amable","Tacaño","Valiente","Alegre"], correcta:1, explicacion:"Tacaño es lo contrario."},
    {id:110, pregunta:"Una receta de cocina es un texto:", opciones:["Narrativo","Descriptivo","Instructivo","Argumentativo"], correcta:2, explicacion:"Da instrucciones paso a paso."},
    {id:111, pregunta:"Verbo en 'María come una manzana':", opciones:["María","come","una","manzana"], correcta:1, explicacion:"'Come' es la acción."},
    {id:112, pregunta:"'Sus cabellos de oro' es:", opciones:["Símil","Metáfora","Hipérbole","Personificación"], correcta:1, explicacion:"Identifica cabello = oro directamente."},
    {id:113, pregunta:"Plural de 'lápiz':", opciones:["Lápizes","Lápices","Lápizs","Lápis"], correcta:1, explicacion:"z → c antes de e."},
    {id:114, pregunta:"Un sustantivo abstracto nombra:", opciones:["Algo que se toca","Ideas o sentimientos","Personas","Lugares"], correcta:1, explicacion:"Ej: amor, libertad, felicidad."},
    {id:115, pregunta:"'¡Qué bonito día!' es oración:", opciones:["Interrogativa","Imperativa","Exclamativa","Enunciativa"], correcta:2, explicacion:"Signos de exclamación → exclamativa."},
    {id:116, pregunta:"Conjunción que une ideas opuestas:", opciones:["Y","O","Pero","Ni"], correcta:2, explicacion:"'Pero' = adversativa."},
    {id:117, pregunta:"¿Cuántas conjugaciones hay en español?", opciones:["1","2","3","4"], correcta:2, explicacion:"-ar (1ª), -er (2ª), -ir (3ª)."},
    {id:118, pregunta:"¿Qué es una palabra compuesta?", opciones:["Con prefijo","Formada por dos+ palabras","Muy larga","Técnica"], correcta:1, explicacion:"Ej: sacapuntas, paraguas."},
    {id:119, pregunta:"CD en 'Juan lee un libro':", opciones:["Juan","lee","un libro","No tiene"], correcta:2, explicacion:"'Un libro' es lo que lee → CD."},
    {id:120, pregunta:"¿Qué es la personificación?", opciones:["Comparar dos cosas","Dar cualidades humanas a objetos","Exagerar","Repetir palabras"], correcta:1, explicacion:"Atribuye cualidades humanas a no humanos."},
    {id:121, pregunta:"¿Qué es un hiato?", opciones:["Dos vocales en misma sílaba","Dos vocales en sílabas separadas","Consonante doble","Sonido mudo"], correcta:1, explicacion:"Vocales contiguas en sílabas distintas."},
    {id:122, pregunta:"Predicado de 'Los niños juegan en el parque':", opciones:["Los niños","juegan","en el parque","juegan en el parque"], correcta:3, explicacion:"Todo lo que se dice del sujeto."},
    {id:123, pregunta:"Narrador que lo sabe todo:", opciones:["Protagonista","Testigo","Omnisciente","Objetivo"], correcta:2, explicacion:"Omnisciente = conoce todos los pensamientos."},
    {id:124, pregunta:"¿Qué es un sinónimo?", opciones:["Significado opuesto","Significado igual/similar","Suena igual","Distinta escritura"], correcta:1, explicacion:"Palabras con significado igual o parecido."},
    {id:125, pregunta:"'Vivir' pertenece a la conjugación:", opciones:["Primera","Segunda","Tercera","Ninguna"], correcta:2, explicacion:"-ir = tercera conjugación."},
    {id:126, pregunta:"Texto argumentativo:", opciones:["Cuenta historia","Describe lugar","Defiende opinión con razones","Da instrucciones"], correcta:2, explicacion:"Presenta y defiende una opinión."},
    {id:127, pregunta:"Diminutivo de 'casa':", opciones:["Casón","Casita","Caserón","Casucha"], correcta:1, explicacion:"Casita = diminutivo."},
    {id:128, pregunta:"¿Qué es el sujeto elíptico?", opciones:["Sujeto largo","Sujeto omitido","Sujeto compuesto","Sujeto pronombre"], correcta:1, explicacion:"No aparece explícito pero se sobreentiende."},
    {id:129, pregunta:"Novelas y cuentos son género:", opciones:["Lírico","Dramático","Narrativo","Épico"], correcta:2, explicacion:"Género narrativo."},
    {id:130, pregunta:"Parte invariable de la palabra:", opciones:["Desinencia","Raíz/lexema","Prefijo","Sufijo"], correcta:1, explicacion:"La raíz contiene el significado base."},
    {id:131, pregunta:"¿Qué es una onomatopeya?", opciones:["Imita un sonido","Palabra inventada","Palabra antigua","Palabra técnica"], correcta:0, explicacion:"Ej: miau, boom, tic-tac."},
    {id:132, pregunta:"Pretérito perfecto simple de 'yo comer':", opciones:["Yo comí","Yo comía","Yo comeré","Yo he comido"], correcta:0, explicacion:"Comí = pretérito perfecto simple."},
    {id:133, pregunta:"Determinante en 'Los gatos negros':", opciones:["gatos","negros","Los","No hay"], correcta:2, explicacion:"'Los' = artículo determinado."},
    {id:134, pregunta:"¿Qué es la aliteración?", opciones:["Repetición de sonidos consonánticos","Exageración","Comparación","Contradicción"], correcta:0, explicacion:"Repetición de sonidos similares."},
    {id:135, pregunta:"Oración compuesta:", opciones:["El sol brilla.","María come y Juan lee.","Llueve mucho.","El niño corre rápido."], correcta:1, explicacion:"Dos verbos (come, lee) unidos por 'y'."},
    {id:136, pregunta:"¿Qué es un campo semántico?", opciones:["Palabras de misma familia","Palabras que comparten tema","Palabras que riman","Mismo prefijo"], correcta:1, explicacion:"Ej: campo semántico de colores."},
    {id:137, pregunta:"Función del adjetivo:", opciones:["Indica acción","Nombra personas","Califica al sustantivo","Une oraciones"], correcta:2, explicacion:"El adjetivo describe o califica."},
    {id:138, pregunta:"'Tengo un hambre que me muero' es:", opciones:["Metáfora","Personificación","Hipérbole","Símil"], correcta:2, explicacion:"Exageración = hipérbole."},
    {id:139, pregunta:"'Detrás' es:", opciones:["Sustantivo","Adjetivo","Adverbio de lugar","Pronombre"], correcta:2, explicacion:"Indica lugar."},
    {id:140, pregunta:"¿Qué es un prefijo?", opciones:["Va al final","Va al inicio","La raíz","Un verbo"], correcta:1, explicacion:"Ej: des-hacer, in-útil."},
    {id:141, pregunta:"CC de lugar en 'Jugamos en el patio':", opciones:["Jugamos","en el patio","el patio","No tiene"], correcta:1, explicacion:"'En el patio' = dónde."},
    {id:142, pregunta:"Autor de Don Quijote:", opciones:["Lope de Vega","García Lorca","Cervantes","Bécquer"], correcta:2, explicacion:"Miguel de Cervantes Saavedra."},
    {id:143, pregunta:"Texto expositivo:", opciones:["Cuenta aventura","Informa y explica","Da órdenes","Expresa sentimientos"], correcta:1, explicacion:"Fin = informar y explicar."},
    {id:144, pregunta:"'Ellos' es:", opciones:["Sustantivo","Adverbio","Pronombre personal","Adjetivo"], correcta:2, explicacion:"3ª persona del plural."},
    {id:145, pregunta:"Agudas llevan tilde cuando:", opciones:["Terminan en consonante","Terminan en vocal, n o s","Siempre","Nunca"], correcta:1, explicacion:"Ej: canción, café, compás."},
    {id:146, pregunta:"Modo subjuntivo de 'cantar' (yo):", opciones:["Canto","Cante","Cantaré","Canté"], correcta:1, explicacion:"'Cante' = presente de subjuntivo."},
    {id:147, pregunta:"'Se' con 'b' o 'v': 'tu__o':", opciones:["Depende: tubo (objeto) / tuvo (verbo)","Siempre b","Siempre v","Ninguna"], correcta:0, explicacion:"Tubo=cilindro (b), tuvo=tener (v)."},
    {id:148, pregunta:"Oración interrogativa indirecta:", opciones:["Con signos ¿?","Sin signos dentro de otra oración","Una orden","Una exclamación"], correcta:1, explicacion:"Ej: No sé qué hora es."},
    {id:149, pregunta:"¿Qué es un sufijo?", opciones:["Va al inicio","Va al final de la raíz","Es la raíz","Es un verbo"], correcta:1, explicacion:"Ej: libr-ería, flor-ista."},
    {id:150, pregunta:"¿Cuántas sílabas tiene 'murciélago'?", opciones:["3","4","5","6"], correcta:1, explicacion:"Mur-cié-la-go = 4 sílabas."},
  ],

  // ===================== CIENCIAS NATURALES (40) =====================
  naturales: [
    {id:201, pregunta:"¿Cuál es la unidad básica de los seres vivos?", opciones:["Átomo","Molécula","Célula","Tejido"], correcta:2, explicacion:"La célula es la unidad estructural y funcional."},
    {id:202, pregunta:"¿Qué órgano bombea la sangre?", opciones:["Pulmones","Hígado","Corazón","Riñones"], correcta:2, explicacion:"El corazón bombea sangre por el cuerpo."},
    {id:203, pregunta:"¿Qué gas necesitan las plantas para la fotosíntesis?", opciones:["Oxígeno","Nitrógeno","CO₂","Hidrógeno"], correcta:2, explicacion:"Las plantas usan CO₂ + luz → glucosa + O₂."},
    {id:204, pregunta:"¿Cuántos huesos tiene el cuerpo humano adulto (aprox.)?", opciones:["106","206","306","406"], correcta:1, explicacion:"El esqueleto adulto tiene unos 206 huesos."},
    {id:205, pregunta:"¿Qué tipo de energía produce el Sol?", opciones:["Eólica","Nuclear y luminosa","Geotérmica","Hidráulica"], correcta:1, explicacion:"El Sol produce energía nuclear (fusión) que se emite como luz y calor."},
    {id:206, pregunta:"Los animales vertebrados tienen:", opciones:["Exoesqueleto","Columna vertebral","Concha","Cutícula"], correcta:1, explicacion:"Los vertebrados tienen columna vertebral."},
    {id:207, pregunta:"¿Qué aparato transforma los alimentos en nutrientes?", opciones:["Respiratorio","Circulatorio","Digestivo","Excretor"], correcta:2, explicacion:"El aparato digestivo procesa los alimentos."},
    {id:208, pregunta:"Estado de la materia con forma y volumen fijo:", opciones:["Sólido","Líquido","Gaseoso","Plasma"], correcta:0, explicacion:"Los sólidos mantienen forma y volumen."},
    {id:209, pregunta:"¿Qué es un ecosistema?", opciones:["Solo los animales de un lugar","Solo las plantas","Seres vivos + medio físico que interactúan","Solo el clima"], correcta:2, explicacion:"Ecosistema = seres vivos + medio abiótico."},
    {id:210, pregunta:"¿Qué planeta es el más cercano al Sol?", opciones:["Venus","Tierra","Mercurio","Marte"], correcta:2, explicacion:"Mercurio es el más cercano al Sol."},
    {id:211, pregunta:"La fotosíntesis ocurre en:", opciones:["Las raíces","Los cloroplastos de las hojas","El tallo","Las flores"], correcta:1, explicacion:"Los cloroplastos contienen clorofila."},
    {id:212, pregunta:"¿Qué son los consumidores primarios?", opciones:["Carnívoros","Herbívoros","Descomponedores","Productores"], correcta:1, explicacion:"Los herbívoros comen plantas directamente."},
    {id:213, pregunta:"¿Cuál es la función del sistema nervioso?", opciones:["Transportar oxígeno","Digerir alimentos","Coordinar y controlar el cuerpo","Filtrar la sangre"], correcta:2, explicacion:"El sistema nervioso coordina todas las funciones."},
    {id:214, pregunta:"¿Qué tipo de roca se forma por enfriamiento de magma?", opciones:["Sedimentaria","Metamórfica","Ígnea","Orgánica"], correcta:2, explicacion:"Las rocas ígneas se forman al enfriarse el magma."},
    {id:215, pregunta:"Los anfibios respiran por:", opciones:["Solo pulmones","Solo branquias","Piel y pulmones (adultos)","Solo piel"], correcta:2, explicacion:"Los anfibios adultos usan piel y pulmones."},
    {id:216, pregunta:"¿Qué es la cadena alimentaria?", opciones:["Lista de alimentos","Secuencia de quién come a quién","Receta de cocina","Tipo de célula"], correcta:1, explicacion:"Muestra la transferencia de energía entre organismos."},
    {id:217, pregunta:"Órgano que filtra la sangre y produce orina:", opciones:["Hígado","Corazón","Riñón","Estómago"], correcta:2, explicacion:"Los riñones filtran la sangre."},
    {id:218, pregunta:"¿Qué es la condensación?", opciones:["Gas → líquido","Líquido → gas","Sólido → líquido","Líquido → sólido"], correcta:0, explicacion:"Condensación = gas se convierte en líquido."},
    {id:219, pregunta:"¿Cuál es el hueso más largo del cuerpo?", opciones:["Húmero","Tibia","Fémur","Radio"], correcta:2, explicacion:"El fémur (en el muslo) es el más largo."},
    {id:220, pregunta:"Las plantas se reproducen sexualmente mediante:", opciones:["Raíces","Hojas","Flores (semillas)","Tallo"], correcta:2, explicacion:"Las flores producen semillas = reproducción sexual."},
    {id:221, pregunta:"¿Qué es un ser vivo autótrofo?", opciones:["Come otros seres","Produce su propio alimento","No necesita agua","Vive sin luz"], correcta:1, explicacion:"Autótrofos fabrican su alimento (ej: plantas)."},
    {id:222, pregunta:"¿Qué tipo de articulación tiene el codo?", opciones:["Fija","Semimóvil","Móvil","No tiene"], correcta:2, explicacion:"El codo es una articulación móvil."},
    {id:223, pregunta:"Los hongos son:", opciones:["Plantas","Animales","Ni plantas ni animales","Bacterias"], correcta:2, explicacion:"Los hongos tienen su propio reino."},
    {id:224, pregunta:"¿Qué gas expulsamos al respirar?", opciones:["Oxígeno","Nitrógeno","CO₂","Helio"], correcta:2, explicacion:"Exhalamos dióxido de carbono."},
    {id:225, pregunta:"Energía renovable:", opciones:["Petróleo","Gas natural","Solar","Carbón"], correcta:2, explicacion:"La energía solar es renovable e inagotable."},
    {id:226, pregunta:"¿Qué es la mitosis?", opciones:["Muerte celular","División celular","Nutrición celular","Respiración celular"], correcta:1, explicacion:"Mitosis = división de una célula en dos iguales."},
    {id:227, pregunta:"Los insectos tienen:", opciones:["4 patas","6 patas","8 patas","10 patas"], correcta:1, explicacion:"Los insectos son artrópodos con 6 patas."},
    {id:228, pregunta:"¿Cuál es la capa de la Tierra donde vivimos?", opciones:["Manto","Núcleo","Corteza","Astenosfera"], correcta:2, explicacion:"Vivimos sobre la corteza terrestre."},
    {id:229, pregunta:"¿Qué vitamina aporta el Sol a nuestra piel?", opciones:["Vitamina A","Vitamina B","Vitamina C","Vitamina D"], correcta:3, explicacion:"El sol ayuda a sintetizar vitamina D."},
    {id:230, pregunta:"Mezcla homogénea:", opciones:["Ensalada","Agua con sal disuelta","Arena y piedras","Aceite y agua"], correcta:1, explicacion:"Agua salada = mezcla homogénea (no se ven los componentes)."},
    {id:231, pregunta:"Los mamíferos se caracterizan por:", opciones:["Poner huevos","Tener escamas","Amamantar a sus crías","Respirar por branquias"], correcta:2, explicacion:"Los mamíferos producen leche para sus crías."},
    {id:232, pregunta:"¿Qué es la erosión?", opciones:["Crecimiento de montañas","Desgaste del terreno por agentes externos","Erupción volcánica","Formación de ríos"], correcta:1, explicacion:"Erosión = desgaste por agua, viento, hielo."},
    {id:233, pregunta:"¿Qué órgano produce la bilis?", opciones:["Estómago","Páncreas","Hígado","Intestino"], correcta:2, explicacion:"El hígado produce bilis para digerir grasas."},
    {id:234, pregunta:"Un circuito eléctrico necesita:", opciones:["Solo cables","Fuente de energía, conductor y receptor","Solo una bombilla","Solo una pila"], correcta:1, explicacion:"Necesita fuente, conductor y receptor mínimo."},
    {id:235, pregunta:"Las bacterias son seres:", opciones:["Pluricelulares","Unicelulares","No son seres vivos","Son virus"], correcta:1, explicacion:"Las bacterias son organismos unicelulares."},
    {id:236, pregunta:"¿Qué sentido controla el oído interno además de oír?", opciones:["Vista","Gusto","Equilibrio","Olfato"], correcta:2, explicacion:"El oído interno controla el equilibrio."},
    {id:237, pregunta:"Los reptiles son animales de sangre:", opciones:["Caliente","Fría (ectotérmicos)","No tienen sangre","Templada"], correcta:1, explicacion:"Son ectotérmicos: regulan Tª con el ambiente."},
    {id:238, pregunta:"¿Qué es la polinización?", opciones:["Caída de hojas","Transporte de polen entre flores","Germinación","Fotosíntesis"], correcta:1, explicacion:"Polinización = transporte de polen (por viento, insectos…)."},
    {id:239, pregunta:"Propiedad de los imanes:", opciones:["Conducen electricidad","Atraen metales ferrosos","Producen luz","Generan calor"], correcta:1, explicacion:"Los imanes atraen hierro y otros metales ferrosos."},
    {id:240, pregunta:"¿Qué es la biodiversidad?", opciones:["Un tipo de planta","Variedad de seres vivos en un lugar","Un ecosistema acuático","Una enfermedad"], correcta:1, explicacion:"Biodiversidad = variedad de vida."},
  ],

  // ===================== CIENCIAS SOCIALES (40) =====================
  sociales: [
    {id:301, pregunta:"¿Cuál es la capital de España?", opciones:["Barcelona","Sevilla","Madrid","Valencia"], correcta:2, explicacion:"Madrid es la capital de España."},
    {id:302, pregunta:"¿En qué continente está España?", opciones:["América","Asia","África","Europa"], correcta:3, explicacion:"España está en Europa."},
    {id:303, pregunta:"¿Cuántas comunidades autónomas tiene España?", opciones:["15","17","19","21"], correcta:1, explicacion:"España tiene 17 comunidades autónomas + 2 ciudades autónomas."},
    {id:304, pregunta:"¿Qué río es el más largo de España?", opciones:["Ebro","Guadalquivir","Tajo","Duero"], correcta:2, explicacion:"El Tajo es el más largo de la Península Ibérica."},
    {id:305, pregunta:"¿Qué océano baña la costa oeste de España?", opciones:["Pacífico","Índico","Atlántico","Ártico"], correcta:2, explicacion:"El océano Atlántico baña la costa oeste."},
    {id:306, pregunta:"¿En qué año llegó Colón a América?", opciones:["1482","1492","1502","1512"], correcta:1, explicacion:"Cristóbal Colón llegó a América en 1492."},
    {id:307, pregunta:"¿Qué es una democracia?", opciones:["Gobierno de un rey","Gobierno del pueblo","Gobierno militar","Gobierno de un dictador"], correcta:1, explicacion:"Democracia = el poder reside en el pueblo."},
    {id:308, pregunta:"¿Cuál es la cordillera más alta de España?", opciones:["Pirineos","Sierra Nevada","Cordillera Cantábrica","Sistema Ibérico"], correcta:0, explicacion:"Los Pirineos tienen las cumbres más altas de la Península."},
    {id:309, pregunta:"¿Qué institución aprueba las leyes en España?", opciones:["El Rey","Las Cortes Generales","El Presidente","Los Ayuntamientos"], correcta:1, explicacion:"Las Cortes (Congreso + Senado) aprueban las leyes."},
    {id:310, pregunta:"La Constitución Española es de:", opciones:["1968","1975","1978","1982"], correcta:2, explicacion:"La Constitución se aprobó en 1978."},
    {id:311, pregunta:"¿Qué clima predomina en las Islas Canarias?", opciones:["Continental","Oceánico","Subtropical","Mediterráneo"], correcta:2, explicacion:"Canarias tiene clima subtropical."},
    {id:312, pregunta:"¿Qué civilización construyó el Coliseo?", opciones:["Griega","Egipcia","Romana","Fenicia"], correcta:2, explicacion:"El Coliseo fue construido por los romanos."},
    {id:313, pregunta:"¿Cuál es la moneda de la Unión Europea?", opciones:["Dólar","Libra","Euro","Peseta"], correcta:2, explicacion:"El euro (€) es la moneda común."},
    {id:314, pregunta:"Sector económico de la agricultura:", opciones:["Primario","Secundario","Terciario","Cuaternario"], correcta:0, explicacion:"Agricultura, ganadería y pesca = sector primario."},
    {id:315, pregunta:"¿Qué es la Edad Media?", opciones:["S. V al XV","S. I al V","S. XV al XVIII","S. XVIII al XX"], correcta:0, explicacion:"Edad Media = caída de Roma (476) hasta 1492 aprox."},
    {id:316, pregunta:"¿Qué país NO pertenece a la UE?", opciones:["Francia","Alemania","Suiza","Italia"], correcta:2, explicacion:"Suiza no es miembro de la UE."},
    {id:317, pregunta:"¿Cuál es el pico más alto de España?", opciones:["Mulhacén","Aneto","Teide","Veleta"], correcta:2, explicacion:"El Teide (Tenerife) con 3.718 m es el más alto de España."},
    {id:318, pregunta:"Los meridianos indican:", opciones:["Latitud","Longitud","Altitud","Profundidad"], correcta:1, explicacion:"Los meridianos miden la longitud (este-oeste)."},
    {id:319, pregunta:"¿Qué es la densidad de población?", opciones:["Total de habitantes","Habitantes por km²","Superficie de un país","Natalidad"], correcta:1, explicacion:"Densidad = habitantes / superficie."},
    {id:320, pregunta:"¿Quién fue el primer rey de España unificada (Reyes Católicos)?", opciones:["Carlos I","Felipe II","Fernando e Isabel","Alfonso X"], correcta:2, explicacion:"Fernando de Aragón e Isabel de Castilla unificaron reinos."},
    {id:321, pregunta:"¿Qué mar baña la costa este de España?", opciones:["Mar del Norte","Mar Negro","Mar Mediterráneo","Mar Rojo"], correcta:2, explicacion:"El Mediterráneo baña la costa este."},
    {id:322, pregunta:"¿Qué es la migración?", opciones:["Tipo de clima","Desplazamiento de personas entre lugares","Tipo de gobierno","Tipo de relieve"], correcta:1, explicacion:"Migración = movimiento de población."},
    {id:323, pregunta:"La Revolución Francesa fue en:", opciones:["1689","1789","1889","1589"], correcta:1, explicacion:"La Revolución Francesa comenzó en 1789."},
    {id:324, pregunta:"¿Qué son las Islas Baleares?", opciones:["Archipiélago en el Atlántico","Archipiélago en el Mediterráneo","Montañas","Ríos"], correcta:1, explicacion:"Mallorca, Menorca, Ibiza y Formentera están en el Mediterráneo."},
    {id:325, pregunta:"Sector económico de las fábricas:", opciones:["Primario","Secundario","Terciario","Cuaternario"], correcta:1, explicacion:"Industria y construcción = sector secundario."},
    {id:326, pregunta:"¿Qué es un mapa político?", opciones:["Muestra relieve","Muestra fronteras y capitales","Muestra clima","Muestra vegetación"], correcta:1, explicacion:"Mapa político = fronteras, países, capitales."},
    {id:327, pregunta:"¿Quiénes eran los visigodos?", opciones:["Pueblo romano","Pueblo germánico","Pueblo árabe","Pueblo celta"], correcta:1, explicacion:"Los visigodos eran un pueblo germánico."},
    {id:328, pregunta:"¿Qué es el PIB?", opciones:["Población Interior Bruta","Producto Interior Bruto","Precio Internacional Base","Plan de Inversión Bancaria"], correcta:1, explicacion:"PIB = valor total de bienes y servicios producidos."},
    {id:329, pregunta:"¿En qué año terminó la Guerra Civil Española?", opciones:["1936","1939","1945","1975"], correcta:1, explicacion:"La Guerra Civil terminó en 1939."},
    {id:330, pregunta:"¿Cuál es el río más caudaloso de España?", opciones:["Tajo","Ebro","Guadalquivir","Duero"], correcta:1, explicacion:"El Ebro es el más caudaloso."},
    {id:331, pregunta:"¿Qué son los paralelos?", opciones:["Líneas verticales","Líneas horizontales que miden latitud","Tipos de clima","Tipos de relieve"], correcta:1, explicacion:"Paralelos = líneas horizontales, miden latitud."},
    {id:332, pregunta:"España es una:", opciones:["República","Monarquía parlamentaria","Dictadura","Monarquía absoluta"], correcta:1, explicacion:"España es una monarquía parlamentaria."},
    {id:333, pregunta:"¿Qué pueblo ocupó la Península Ibérica durante 800 años?", opciones:["Romanos","Vikingos","Musulmanes","Griegos"], correcta:2, explicacion:"Los musulmanes estuvieron del 711 al 1492."},
    {id:334, pregunta:"¿Qué es el éxodo rural?", opciones:["Ir del campo a la ciudad","Ir de la ciudad al campo","Viajar al extranjero","Cambiar de trabajo"], correcta:0, explicacion:"Éxodo rural = migración del campo a la ciudad."},
    {id:335, pregunta:"La ONU se fundó en:", opciones:["1918","1939","1945","1950"], correcta:2, explicacion:"La ONU se fundó en 1945 tras la II Guerra Mundial."},
    {id:336, pregunta:"¿Cuál es la comunidad autónoma más grande de España?", opciones:["Andalucía","Castilla y León","Cataluña","Extremadura"], correcta:1, explicacion:"Castilla y León es la más extensa."},
    {id:337, pregunta:"¿Qué es el cambio climático?", opciones:["Cambio de estación","Alteración global del clima por actividad humana","Tipo de viento","Cambio de hora"], correcta:1, explicacion:"Calentamiento global por emisiones de gases."},
    {id:338, pregunta:"Los Derechos Humanos se proclamaron en:", opciones:["1918","1936","1948","1978"], correcta:2, explicacion:"Declaración Universal de Derechos Humanos: 1948."},
    {id:339, pregunta:"¿Qué es una meseta?", opciones:["Montaña alta","Llanura elevada","Valle profundo","Isla"], correcta:1, explicacion:"Meseta = terreno elevado y llano."},
    {id:340, pregunta:"Sector económico del turismo:", opciones:["Primario","Secundario","Terciario","Cuaternario"], correcta:2, explicacion:"Servicios (turismo, comercio…) = sector terciario."},
  ],

  // ===================== INGLÉS (40) =====================
  ingles: [
    {id:401, pregunta:"Choose the correct form: 'She ___ to school every day.'", opciones:["go","goes","going","gone"], correcta:1, explicacion:"Third person singular → goes."},
    {id:402, pregunta:"What is the past tense of 'eat'?", opciones:["eated","eat","ate","eaten"], correcta:2, explicacion:"Eat → ate (irregular verb)."},
    {id:403, pregunta:"Translate: 'mariposa'", opciones:["Bird","Butterfly","Bee","Bat"], correcta:1, explicacion:"Mariposa = butterfly."},
    {id:404, pregunta:"Complete: 'There ___ many books on the table.'", opciones:["is","are","am","be"], correcta:1, explicacion:"Plural (books) → There are."},
    {id:405, pregunta:"What is the opposite of 'hot'?", opciones:["Warm","Cool","Cold","Wet"], correcta:2, explicacion:"Hot ↔ Cold."},
    {id:406, pregunta:"Choose: 'I ___ watching TV now.'", opciones:["am","is","are","be"], correcta:0, explicacion:"I + am = present continuous."},
    {id:407, pregunta:"What day comes after Wednesday?", opciones:["Monday","Tuesday","Thursday","Friday"], correcta:2, explicacion:"Wednesday → Thursday."},
    {id:408, pregunta:"Plural of 'child':", opciones:["Childs","Childes","Children","Childrens"], correcta:2, explicacion:"Child → children (irregular)."},
    {id:409, pregunta:"'Can I have some water?' is a:", opciones:["Command","Request","Statement","Exclamation"], correcta:1, explicacion:"It's politely asking = request."},
    {id:410, pregunta:"Complete: 'The cat is ___ the table.'", opciones:["in","on","under","at"], correcta:2, explicacion:"Under = debajo de la mesa."},
    {id:411, pregunta:"What colour do you get mixing blue and yellow?", opciones:["Red","Green","Orange","Purple"], correcta:1, explicacion:"Blue + yellow = green."},
    {id:412, pregunta:"Past simple of 'go':", opciones:["goed","gone","went","going"], correcta:2, explicacion:"Go → went (irregular)."},
    {id:413, pregunta:"'She is taller ___ her brother.'", opciones:["that","then","than","the"], correcta:2, explicacion:"Comparatives use 'than'."},
    {id:414, pregunta:"Which is a fruit?", opciones:["Carrot","Potato","Strawberry","Onion"], correcta:2, explicacion:"Strawberry = fresa (fruit)."},
    {id:415, pregunta:"'Must' expresses:", opciones:["Ability","Permission","Obligation","Preference"], correcta:2, explicacion:"Must = obligation/necessity."},
    {id:416, pregunta:"Complete: 'They ___ play football yesterday.'", opciones:["doesn't","didn't","don't","isn't"], correcta:1, explicacion:"Past simple negative → didn't."},
    {id:417, pregunta:"How many months have 31 days?", opciones:["5","6","7","8"], correcta:2, explicacion:"Jan, Mar, May, Jul, Aug, Oct, Dec = 7 months."},
    {id:418, pregunta:"'Beautiful' is a/an:", opciones:["Noun","Verb","Adjective","Adverb"], correcta:2, explicacion:"Beautiful describes something = adjective."},
    {id:419, pregunta:"What time is 'quarter past three'?", opciones:["3:45","3:30","3:15","3:25"], correcta:2, explicacion:"Quarter past = :15 → 3:15."},
    {id:420, pregunta:"Complete: 'I have ___ been to London.'", opciones:["ever","never","yet","already"], correcta:1, explicacion:"Never = nunca → I have never been."},
    {id:421, pregunta:"Translate: 'biblioteca'", opciones:["Bookshop","Library","School","Office"], correcta:1, explicacion:"Biblioteca = library."},
    {id:422, pregunta:"'Will' is used for:", opciones:["Past actions","Present habits","Future predictions","Past habits"], correcta:2, explicacion:"Will + verb = future."},
    {id:423, pregunta:"Superlative of 'big':", opciones:["Bigger","Most big","Biggest","More big"], correcta:2, explicacion:"Big → bigger → biggest."},
    {id:424, pregunta:"Which is NOT a season?", opciones:["Spring","Autumn","Monday","Winter"], correcta:2, explicacion:"Monday is a day, not a season."},
    {id:425, pregunta:"'Could you help me?' is:", opciones:["An order","A polite request","A statement","A question about ability"], correcta:1, explicacion:"Could you…? = polite request."},
    {id:426, pregunta:"Translate: 'tormenta'", opciones:["Storm","Cloud","Rain","Wind"], correcta:0, explicacion:"Tormenta = storm."},
    {id:427, pregunta:"Complete: 'She ___ her homework at 5 pm yesterday.'", opciones:["does","did","doing","done"], correcta:1, explicacion:"Yesterday → past simple → did."},
    {id:428, pregunta:"Which word rhymes with 'cat'?", opciones:["Cut","Car","Hat","Cup"], correcta:2, explicacion:"Cat – hat (riman)."},
    {id:429, pregunta:"'Some' is used in:", opciones:["Negative sentences","Questions and affirmative","Only questions","Only negative"], correcta:1, explicacion:"Some → affirmative and offers/requests."},
    {id:430, pregunta:"What is the third month of the year?", opciones:["February","March","April","May"], correcta:1, explicacion:"January, February, March = 3rd."},
    {id:431, pregunta:"'Quickly' is a/an:", opciones:["Noun","Adjective","Verb","Adverb"], correcta:3, explicacion:"Quickly describes how → adverb."},
    {id:432, pregunta:"Complete: 'If it rains, I ___ stay home.'", opciones:["will","would","am","did"], correcta:0, explicacion:"First conditional: If + present, will + verb."},
    {id:433, pregunta:"Opposite of 'expensive':", opciones:["Cheap","Rich","Poor","Free"], correcta:0, explicacion:"Expensive ↔ cheap."},
    {id:434, pregunta:"'Have to' expresses:", opciones:["Ability","Possibility","Obligation","Wish"], correcta:2, explicacion:"Have to = external obligation."},
    {id:435, pregunta:"Which is a wild animal?", opciones:["Dog","Cat","Wolf","Hamster"], correcta:2, explicacion:"Wolf (lobo) = wild animal."},
    {id:436, pregunta:"Complete: 'I ___ swim when I was 5.'", opciones:["can","could","will","may"], correcta:1, explicacion:"Past ability → could."},
    {id:437, pregunta:"Translate: 'estrella'", opciones:["Sun","Moon","Star","Sky"], correcta:2, explicacion:"Estrella = star."},
    {id:438, pregunta:"Present continuous: 'They ___ (play) now.'", opciones:["plays","played","are playing","play"], correcta:2, explicacion:"Now → present continuous → are playing."},
    {id:439, pregunta:"Which preposition: 'I arrive ___ Monday.'", opciones:["in","on","at","by"], correcta:1, explicacion:"Days → on (on Monday)."},
    {id:440, pregunta:"'Whose book is this?' asks about:", opciones:["Place","Time","Possession","Reason"], correcta:2, explicacion:"Whose = de quién → possession."},
  ],

  // ===================== EDUCACIÓN ARTÍSTICA (20) =====================
  artistica: [
    {id:501, pregunta:"Colores primarios en pintura:", opciones:["Rojo, verde, azul","Rojo, amarillo, azul","Naranja, verde, violeta","Blanco, negro, gris"], correcta:1, explicacion:"Primarios en pintura: rojo, amarillo y azul."},
    {id:502, pregunta:"¿Qué es una escala musical?", opciones:["Instrumento","Sucesión ordenada de notas","Tipo de danza","Pintura"], correcta:1, explicacion:"Sucesión de notas de grave a agudo."},
    {id:503, pregunta:"¿Cuántas notas tiene la escala musical occidental?", opciones:["5","6","7","8"], correcta:2, explicacion:"Do, Re, Mi, Fa, Sol, La, Si = 7 notas."},
    {id:504, pregunta:"¿Qué artista pintó 'La noche estrellada'?", opciones:["Picasso","Dalí","Van Gogh","Monet"], correcta:2, explicacion:"Vincent van Gogh la pintó en 1889."},
    {id:505, pregunta:"Mezclar rojo + amarillo da:", opciones:["Verde","Naranja","Violeta","Marrón"], correcta:1, explicacion:"Rojo + amarillo = naranja."},
    {id:506, pregunta:"¿Qué es el pentagrama?", opciones:["Figura geométrica","5 líneas donde se escribe música","Instrumento","Tipo de danza"], correcta:1, explicacion:"Pentagrama = 5 líneas paralelas para notación musical."},
    {id:507, pregunta:"¿Qué técnica usa puntos pequeños para crear imágenes?", opciones:["Acuarela","Puntillismo","Collage","Grafiti"], correcta:1, explicacion:"Puntillismo = técnica con puntos de color."},
    {id:508, pregunta:"Un instrumento de viento:", opciones:["Guitarra","Batería","Flauta","Piano"], correcta:2, explicacion:"La flauta se toca soplando = viento."},
    {id:509, pregunta:"Colores cálidos:", opciones:["Azul, verde, violeta","Rojo, naranja, amarillo","Blanco, gris, negro","Rosa, lila, celeste"], correcta:1, explicacion:"Cálidos: rojo, naranja, amarillo."},
    {id:510, pregunta:"¿Qué es un autorretrato?", opciones:["Retrato de otra persona","Retrato de uno mismo","Paisaje","Bodegón"], correcta:1, explicacion:"Auto = uno mismo + retrato."},
    {id:511, pregunta:"La guitarra es un instrumento de:", opciones:["Viento","Percusión","Cuerda","Teclado"], correcta:2, explicacion:"Se tocan sus cuerdas = instrumento de cuerda."},
    {id:512, pregunta:"¿Qué es un bodegón?", opciones:["Paisaje","Retrato","Pintura de objetos/alimentos","Escultura"], correcta:2, explicacion:"Bodegón = naturaleza muerta (objetos, frutas…)."},
    {id:513, pregunta:"Mezclar azul + amarillo da:", opciones:["Naranja","Verde","Violeta","Marrón"], correcta:1, explicacion:"Azul + amarillo = verde."},
    {id:514, pregunta:"¿Qué es la simetría?", opciones:["Colores iguales","Dos mitades idénticas respecto a un eje","Líneas paralelas","Figuras grandes"], correcta:1, explicacion:"Simetría = dos mitades iguales."},
    {id:515, pregunta:"Un instrumento de percusión:", opciones:["Violín","Trompeta","Tambor","Arpa"], correcta:2, explicacion:"El tambor se golpea = percusión."},
    {id:516, pregunta:"¿Qué movimiento artístico representa Picasso?", opciones:["Impresionismo","Cubismo","Renacimiento","Surrealismo"], correcta:1, explicacion:"Picasso es el gran referente del cubismo."},
    {id:517, pregunta:"Colores fríos:", opciones:["Rojo, naranja","Azul, verde, violeta","Amarillo, rosa","Blanco, negro"], correcta:1, explicacion:"Fríos: azul, verde, violeta."},
    {id:518, pregunta:"¿Qué es un mosaico?", opciones:["Tipo de música","Composición con piezas pequeñas","Tipo de baile","Instrumento"], correcta:1, explicacion:"Mosaico = imagen formada por teselas o piezas."},
    {id:519, pregunta:"El 'tempo' en música indica:", opciones:["Volumen","Velocidad","Altura","Timbre"], correcta:1, explicacion:"Tempo = velocidad a la que se interpreta."},
    {id:520, pregunta:"Mezclar rojo + azul da:", opciones:["Naranja","Verde","Violeta","Marrón"], correcta:2, explicacion:"Rojo + azul = violeta."},
  ],

  // ===================== VALORES CÍVICOS Y ÉTICOS (20) =====================
  valores: [
    {id:601, pregunta:"¿Qué es la empatía?", opciones:["Ser egoísta","Ponerse en el lugar del otro","Ser tímido","No hablar con nadie"], correcta:1, explicacion:"Empatía = comprender los sentimientos de otros."},
    {id:602, pregunta:"¿Qué documento recoge los derechos fundamentales en España?", opciones:["El diccionario","La Constitución","El periódico","La enciclopedia"], correcta:1, explicacion:"La Constitución de 1978 recoge los derechos."},
    {id:603, pregunta:"¿Qué es la igualdad de género?", opciones:["Que todos vistan igual","Mismos derechos y oportunidades sin importar el género","Que todos piensen igual","Que todos vivan juntos"], correcta:1, explicacion:"Igualdad de género = mismos derechos para todos."},
    {id:604, pregunta:"¿Qué son las 3R del reciclaje?", opciones:["Romper, Reusar, Reciclar","Reducir, Reutilizar, Reciclar","Recoger, Reparar, Revender","Recordar, Repetir, Revisar"], correcta:1, explicacion:"Reducir, Reutilizar, Reciclar."},
    {id:605, pregunta:"¿Qué es el acoso escolar (bullying)?", opciones:["Un juego divertido","Agresión repetida a un compañero","Una asignatura","Un deporte"], correcta:1, explicacion:"Bullying = agresión repetida e intencionada."},
    {id:606, pregunta:"¿Qué derecho tienen todos los niños?", opciones:["Trabajar en fábricas","Ir a la escuela","Conducir coches","Votar en elecciones"], correcta:1, explicacion:"La educación es un derecho fundamental de la infancia."},
    {id:607, pregunta:"¿Qué significa 'solidaridad'?", opciones:["Pensar solo en uno mismo","Ayudar a los demás desinteresadamente","Competir contra todos","Ignorar los problemas"], correcta:1, explicacion:"Solidaridad = colaborar y ayudar sin esperar nada."},
    {id:608, pregunta:"¿Qué es el desarrollo sostenible?", opciones:["Construir mucho","Satisfacer necesidades actuales sin comprometer las futuras","Gastar todos los recursos","No construir nada"], correcta:1, explicacion:"Desarrollo sostenible = equilibrio presente-futuro."},
    {id:609, pregunta:"¿Cuál es un ejemplo de comportamiento cívico?", opciones:["Tirar basura al suelo","Respetar las señales de tráfico","Gritar en la biblioteca","Colarse en la fila"], correcta:1, explicacion:"Respetar normas = civismo."},
    {id:610, pregunta:"¿Qué es la tolerancia?", opciones:["Aceptar solo a quien piensa como tú","Respetar ideas y formas de vida diferentes","No tener opinión","Imponer tus ideas"], correcta:1, explicacion:"Tolerancia = respetar la diversidad."},
    {id:611, pregunta:"¿Qué es la privacidad digital?", opciones:["Compartir todo en redes","Proteger tus datos personales en internet","No usar tecnología","Publicar fotos de otros"], correcta:1, explicacion:"Proteger información personal en internet."},
    {id:612, pregunta:"¿Por qué es importante reciclar?", opciones:["Para ganar dinero","Para reducir contaminación y cuidar el planeta","No es importante","Para ocupar tiempo"], correcta:1, explicacion:"Reciclar reduce residuos y protege el medio ambiente."},
    {id:613, pregunta:"¿Qué es la responsabilidad?", opciones:["Hacer lo que quieras","Cumplir con tus obligaciones y asumir consecuencias","No hacer nada","Culpar a otros"], correcta:1, explicacion:"Responsabilidad = cumplir deberes y asumir actos."},
    {id:614, pregunta:"¿Qué significa 'diversidad cultural'?", opciones:["Todos iguales","Variedad de culturas, lenguas y tradiciones","Solo una cultura","Eliminar tradiciones"], correcta:1, explicacion:"Diversidad = riqueza de culturas conviviendo."},
    {id:615, pregunta:"¿Qué es el voluntariado?", opciones:["Trabajo obligatorio","Ayudar de forma gratuita y voluntaria","Trabajo remunerado","Un castigo"], correcta:1, explicacion:"Voluntariado = ayuda libre y sin cobrar."},
    {id:616, pregunta:"¿Qué es un derecho?", opciones:["Algo que debemos hacer","Algo que podemos exigir y nos protege","Un castigo","Una obligación laboral"], correcta:1, explicacion:"Derechos = garantías que protegen a las personas."},
    {id:617, pregunta:"¿Qué es un deber?", opciones:["Algo opcional","Responsabilidad que debemos cumplir","Un privilegio","Un regalo"], correcta:1, explicacion:"Deber = obligación que tenemos como ciudadanos."},
    {id:618, pregunta:"¿Por qué es malo el ciberacoso?", opciones:["No es malo","Causa daño emocional a la víctima","Es divertido","Solo afecta a adultos"], correcta:1, explicacion:"El ciberacoso causa sufrimiento y es un delito."},
    {id:619, pregunta:"¿Qué es el consumo responsable?", opciones:["Comprar todo lo que veas","Comprar lo necesario cuidando el medio ambiente","No comprar nunca","Comprar solo marcas caras"], correcta:1, explicacion:"Consumir lo necesario minimizando impacto ambiental."},
    {id:620, pregunta:"¿Qué es la paz?", opciones:["Ausencia de guerra y conflictos violentos","Silencio absoluto","No hablar con nadie","Estar solo"], correcta:0, explicacion:"Paz = convivencia sin violencia."},
  ]

};
